spring.application.name=jamipariseva-api
spring.datasource.url=jdbc:postgresql://localhost:5432/jamipariseva
spring.datasource.username =
spring.datasource.password = 

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
